user/urls.py
from django.urls import path
from django.conf.urls import include
from django.views.generic import TemplateView

from . import views

app_name = 'user'

urlpatterns = [
    # Homepage (and logging out, which redirects to homepage)
    path('', views.home, name='home'),
    path('logout', views.logout_view, name='logout'),

    # The User Homepage - essentially the Main Menu
    path('user/', views.get_user, name='main'),

    # Updating the current user's bio (fakeurl is just used to redirect back to the profile after profile creation)
    path('create/', views.getProfileForm, name='newprofile'),
    path('fakeurl/', views.get_profile, name='newprofileform'),
    path('fakeurl2/',views.clear_filter, name='clearfilter'),

    # View other profiles (by id, all of them, or via the roommate searching feature)
    path('<int:prof_id>/', views.getDetail, name='details'),
    #path('list/', views.ProfileIndexView.as_view(), name='profilelist'),
    path('search/', views.profileSearch, name='search'),

    # Submits action of swiping right or left
    path('action/', views.action, name='action'),

    # Matching URLs - viewing matches and sending messages to users
    path('matches/', views.get_matches, name='matches'),
    path('chat/<str:uname>/', views.startMessage, name='chat'),
    path('chat/<str:uname>/send', views.sendMessage, name='sendmessage'),
    path('chat/<str:uname>/<int:prev_msg_id>/send', views.replyMessage, name='replymessage'),
    path('inbox/', views.get_inbox, name='inbox'),
    path('viewMessage/<int:msg_id>', views.viewMessage, name='viewmessage'),
    path('updateMapboxAddress/<int:msg_id>', views.updateMapboxAddress, name='updatemapboxaddress')
]

user/models.py
from django.db import models

# Create your models here.
class TestModel(models.Model):
    text = models.CharField(max_length=200)

g_choices = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other','Other')
    )
p_choices = (
        ('Introvert', 'Introvert'),
        ('Extrovert', 'Extrovert'),
    )
c_choices = (
        ('Have a car', 'Have a car'),
        ('Do not have a car', 'Do not have a car'),
    )
class Profile(models.Model):
    username = models.CharField(max_length=100, default='')
    name_text = models.CharField(default='', max_length=100)
    bio_text = models.CharField(default='',max_length=500)
    age =  models.CharField(default='', max_length=100)
    grad_year = models.CharField(default='', max_length=100)
    budget_lower = models.CharField(default='', max_length=100)
    budget_upper = models.CharField(default='', max_length=100)
    #so technically people said location was super important to them but idk how to implement that
    #maybe people can add addresses of proporties they are interested in?
    noise_level = models.CharField(default='', max_length=100) # 1-10 deal maybe change this to radio buttons 
    
    gender = models.CharField(max_length=100, choices=g_choices, default="")
    
    personality = models.CharField(max_length=100, choices=p_choices, default="")
    location = models.CharField(default='',max_length=1000)
    
    car = models.CharField(max_length=100, choices=c_choices, default="")

    agemin = models.CharField(default='', max_length=100)
    agemax = models.CharField(default='', max_length=100)
    grad_yearmin = models.CharField(default='', max_length=100)
    grad_yearmax = models.CharField(default='', max_length=100)

    budget_lowerfilter = models.CharField(default='', max_length=100)
    budget_upperfilter = models.CharField(default='', max_length=100)
    noise_levelmin = models.CharField(default='', max_length=100) # 1-10 deal maybe change this to radio buttons 
    noise_levelmax = models.CharField(default='', max_length=100) # 1-10 deal maybe change this to radio buttons 
    genderfilter = models.CharField(max_length=100, choices=g_choices, default="")
    personalityfilter = models.CharField(max_length=100, choices=p_choices, default="")
    carfilter = models.CharField(max_length=100, choices=c_choices, default="")

    profile_image = models.ImageField(null = True, blank = True, upload_to= "images/")
    
    def __str__(self):
        return "\n" + self.username + "\n" + self.name_text + "\n" + self.bio_text +"\n" + self.budget_lower +"\n" + self.budget_upper +"\n"+ self.noise_level +"\n"+ self.gender +"\n" + self.personality +"\n"+ self.location +"\n"+ self.car +"\n"


# Model for actions
class Action(models.Model):
    # Takes in the first name
    # Takes in the second name
    # Takes in whether or not they've been checked

    #firstUser = models.ForeignKey(Profile, on_delete = models.CASCADE)
    firstUser = models.CharField(max_length=100, default='')
    secondUser = models.CharField(max_length=100, default='')
    met = models.IntegerField(default = 0)


    def __str__(self):
       return "First: " + self.firstUser + " Second: " + self.secondUser + " Met: " + str(self.met)

# Model for Match Links (i.e. both users swipe right on each other and want to chat via GroupMe)
class MatchLink(models.Model):
    firstUser = models.CharField(max_length=100, default='')
    secondUser = models.CharField(max_length=100, default='')
    url = models.CharField(max_length=300)

    def __str(self):
        return "First: " + self.firstUser + " Second: " + self.secondUser + " GroupMe: " + self.url

""" Contains all of the messages a person has not replied to. """
class Messages(models.Model):
    sender = models.CharField(max_length=100, default='')
    receiver = models.CharField(max_length=100, default='')
    subject = models.CharField(max_length=200, default='')
    message = models.CharField(max_length=1000, default='')
    date = models.DateField(auto_now=False, auto_now_add=True)
    time = models.TimeField(auto_now=False, auto_now_add=True)
    previousMessage = models.IntegerField(default=None, null=True)
    messageCount = models.IntegerField(default=0)
    mapboxLocation = models.CharField(max_length=500, default='')

""" Messages that have been replied to, not displayed in inbox since its a part of a conversation """
""" All messages can in a conversation can be viewed by following the previousMessage until it is null """
class oldMessages(models.Model):
    sender = models.CharField(max_length=100, default='')
    receiver = models.CharField(max_length=100, default='')
    subject = models.CharField(max_length=200, default='')
    message = models.CharField(max_length=1000, default='')
    date = models.DateField()
    time = models.TimeField()
    previousMessage = models.IntegerField(default=None, null=True)
    nextMessage = models.IntegerField(default=None, null=True) 
    messageCount = models.IntegerField(default=0)

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout, login
from .models import Profile, Messages, oldMessages
from .models import g_choices
from .models import p_choices
from .models import c_choices
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.http import HttpResponse
from .models import Action
import requests, json
from collections import OrderedDict

# Create your views here.

def home(request):
    return render(request, 'user/home.html',{})

"""
Displays the user page (which includes links to updating bio, going on the roommate hunt, etc). Redirects to home page if not logged in
"""
def get_user(request):
    if request.user.is_authenticated:
        return render(request, 'user/index.html',{"profile": Profile.objects.filter(username = request.user.username)})
    else:
        return render(request, 'user/home.html',{})

"""
Logs the current user out and redirects to the home page.
"""
def logout_view(request):
    logout(request)
    return render(request, 'user/home.html',{})

"""
Lists all completed profiles
"""
class ProfileIndexView(generic.ListView):
    template_name = 'user/profileList.html'
    context_object_name = 'latest_profile_list'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Profile.objects.order_by('-name_text')[:]

"""
Displays a potential roommate as part of the search, as well as options to swipe left and right.
"""
def profileSearch(request):
    if request.user.is_authenticated:
        actions = Action.objects.filter(firstUser=request.user.username)
        secondUsers = set()
        for action in actions:
            secondUsers.add(action.secondUser)
        profiles = Profile.objects.all()
        context = {}
        currentuser = Profile.objects.get(username=request.user.username)
        for profile in profiles:
            if profile.username == request.user.username:
                continue
            if profile.username not in secondUsers:
                #start filtering here
                if profile.age != "" and currentuser.agemin != "" and int(profile.age) < int(currentuser.agemin):
                    continue
                if profile.age != "" and currentuser.agemax != "" and int(profile.age) > int(currentuser.agemax):
                    continue
                if profile.grad_year != "" and currentuser.grad_yearmin != "" and int(profile.grad_year) < int(currentuser.grad_yearmin):
                    continue
                if profile.grad_year != "" and currentuser.grad_yearmax != "" and int(profile.grad_year) > int(currentuser.grad_yearmax):
                    continue
                if profile.budget_upper != "" and currentuser.budget_lowerfilter != "" and int(profile.budget_upper) < int(currentuser.budget_lowerfilter):
                    continue
                if profile.budget_lower != "" and currentuser.budget_upperfilter != "" and int(profile.budget_lower) > int(currentuser.budget_upperfilter):
                    continue
                if profile.noise_level != "" and currentuser.noise_levelmin != "" and int(profile.noise_level) < int(currentuser.noise_levelmin):
                    continue
                if profile.noise_level != "" and currentuser.noise_levelmax != "" and int(profile.noise_level) > int(currentuser.noise_levelmax):
                    continue
                if profile.gender != "" and currentuser.genderfilter != "" and profile.gender != currentuser.genderfilter:
                    continue
                if profile.personality != "" and currentuser.personalityfilter != "" and profile.personality != currentuser.personalityfilter:
                    continue
                if profile.car != "" and currentuser.carfilter != "" and profile.car != currentuser.carfilter:
                    continue
                context["profile"] = profile
                break
        return render(request, 'user/profileSearch.html', context)
    else:
        return render(request, 'user/home.html',{})

#Action Search
class ActionSearchView(generic.ListView):
    template_name = 'user/profileSearch.html'
    context_object_name = 'latest_profile_list'

    def get_queryset(self):
        return Action.objects.order_by('-firstUser')[:]

def action(request):
    username = None
    if request.user.is_authenticated:
        username = request.user.username

    other = request.POST['username']
    if(request.POST['action'] == 'Left'):
        action = Action(firstUser=username, secondUser=other, met=-1)
    else:
        action = Action(firstUser=username, secondUser=other, met=1)
    action.save()

    return HttpResponseRedirect(reverse('user:search'))


    #Takes both peoples names
    # user1 (You) and user2 (other person)
    # Puts action[user1, user2, -1(Left) or 1 (Right)] in query

    #def get_other(request):
     #   user = None
      #  other = None
       # if Profile.objects.filter(username=username).exists():
        #    action = Action()
 #   def swipe(request, username)


"""
Called when you click on some one's profile you got to see all their details
"""
# class ProfileDetailView(generic.DetailView):
def getDetail(request, prof_id,*args, **kwargs):
    if request.user.is_authenticated:
        currentProfile = Profile.objects.get(pk=prof_id)
        context={"profile":currentProfile, "gchoice":g_choices, "pchoice":p_choices, "cchoice": c_choices}
        return render(request, 'user/detail.html',context)
    else:
        return render(request, 'user/home.html',{})
    # model = Profile
    # template_name = 'user/detail.html'
    # def get_queryset(self):
    #     """
    #     Excludes any questions that aren't published yet.
    #     """
    #     return Profile.objects.order_by('-name_text')[:]

def getProfileForm(request):
    # Makes sure that user is authenticated before allowing them to update/edit their profile
    if request.user.is_authenticated:
        # Sends the current profile with the view so the view can display information about the current profile
        context = {}
        # g_choices = (
        # ('M', 'Introvert'),
        # ('F', 'Extrovert'),
        # ('O','Other/Prefer not to say')
        # )
        # p_choices = (
        # ('I', 'Introvert'),
        # ('E', 'Extrovert'),
        # )
        # c_choices = (
        # ('Y', 'Have a car'),
        # ('N', 'Do not have a car'),
        # )
        if Profile.objects.filter(username=request.user.username).exists():
            currentProfile = Profile.objects.get(username=request.user.username)
            matches = set()
            actionsgrp1 = Action.objects.filter(firstUser=request.user.username,met=1)
            actionsgrp2 = Action.objects.filter(secondUser=request.user.username,met=1)

            for action1 in actionsgrp1:
                for action2 in actionsgrp2:
                    if action1.secondUser == action2.firstUser:
                        matches.add(Profile.objects.get(username=action1.secondUser))
            context = {"profile" : currentProfile, "matches" : matches, "gchoice":g_choices, "pchoice":p_choices, "cchoice": c_choices}
            return render(request, 'user/profile.html', context)
        else:
            context={"gchoice":g_choices, "pchoice":p_choices, "cchoice": c_choices}
            return render(request, 'user/profile.html',context)
    else:
        # The user is not authenticated and should return to the home page
        return render(request, 'user/home.html',{})

"""
Called when a user clicks the button to update/create their profile
"""
def get_profile(request):
    username = None

    # Checks to see if user is authenticated 

    if request.user.is_authenticated:
        username = request.user.username
    
    # If not then redirects back to login at home screen
    if username == None or username == '':
        return render(request, 'user/home.html',{})
    else:
        # Get information from the text fields and update the profile
        if Profile.objects.filter(username=username).exists():
            #If elses check to make sure the field isnt empty so we dont overwrite prexisting data with empty values
            existingProfile = Profile.objects.get(username=username)
            if(request.POST['name_text'] != ""):
                existingProfile.name_text = request.POST['name_text']
            if(request.POST['bio_text'] != ""):
                existingProfile.bio_text = request.POST['bio_text']
            if(request.POST['age'] != ""):
                existingProfile.age = request.POST['age']
            if(request.POST['grad_year'] != ""):
                existingProfile.grad_year = request.POST['grad_year']
            if(request.POST['budget_lower'] != ""):
                existingProfile.budget_lower=request.POST['budget_lower']
            if(request.POST['budget_upper'] != ""):
                existingProfile.budget_upper=request.POST['budget_upper']
            if(existingProfile.budget_upper and existingProfile.budget_lower and int(existingProfile.budget_upper) < int(existingProfile.budget_lower)):
                #make sure they didnt put in nonsenical input
                temp=existingProfile.budget_upper
                existingProfile.budget_upper=existingProfile.budget_lower
                existingProfile.budget_lower=temp
            if(request.POST['noise_level'] != ""):
                existingProfile.noise_level=request.POST['noise_level']
            if 'gender' in request.POST:
                existingProfile.gender=request.POST['gender']
            #if(request.POST['personality'] != ""):
            if 'personality' in request.POST:
                existingProfile.personality=request.POST['personality']
            if(request.POST['location'] != ""):

user/templates/user/chat.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <!--  This file has been downloaded from bootdey.com    @bootdey on twitter -->
    <!--  All snippets are MIT license https://bootdey.com/license -->

    <title>Compose Message</title>
    <link rel="icon" type="image/x-icon" href="{% static 'user/assets/img/portfolio/uvalogo.jpg' %}" />   
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <style type="text/css">


body{margin-top:20px;
background:#FFA500;
}


.inbox .inbox-menu ul {
    margin-top: 30px;
    padding: 0;
    list-style: none
}

.inbox .inbox-menu ul li {
    height: 30px;
    padding: 5px 15px;
    position: relative
}

.inbox .inbox-menu ul li:hover,
.inbox .inbox-menu ul li.active {
    background: #e4e5e6
}

.inbox .inbox-menu ul li.title {
    margin: 20px 0 -5px 0;
    text-transform: uppercase;
    font-size: 10px;
    color: #d1d4d7
}

.inbox .inbox-menu ul li.title:hover {
    background: 0 0
}

.inbox .inbox-menu ul li a {
    display: block;
    width: 100%;
    text-decoration: none;
    color: #3d3f42
}

.inbox .inbox-menu ul li a i {
    margin-right: 10px
}

.inbox .inbox-menu ul li a .label {
    position: absolute;
    top: 10px;
    right: 15px;
    display: block;
    min-width: 14px;
    height: 14px;
    padding: 2px
}

.inbox ul.messages-list {
    list-style: none;
    margin: 15px -15px 0 -15px;
    padding: 15px 15px 0 15px;
    border-top: 1px solid #d1d4d7
}

.inbox ul.messages-list li {
    -webkit-border-radius: 2px;
    -moz-border-radius: 2px;
    border-radius: 2px;
    cursor: pointer;
    margin-bottom: 10px;
    padding: 10px
}

.inbox ul.messages-list li a {
    color: #3d3f42
}

.inbox ul.messages-list li a:hover {
    text-decoration: none
}

.inbox ul.messages-list li.unread .header,
.inbox ul.messages-list li.unread .title {
    font-weight: 700
}

.inbox ul.messages-list li:hover {
    background: #e4e5e6;
    border: 1px solid #d1d4d7;
    padding: 9px
}

.inbox ul.messages-list li:hover .action {
    color: #d1d4d7
}

.inbox ul.messages-list li .header {
    margin: 0 0 5px 0
}

.inbox ul.messages-list li .header .from {
    width: 49.9%;
    white-space: nowrap;
    overflow: hidden!important;
    text-overflow: ellipsis
}

.inbox ul.messages-list li .header .date {
    width: 50%;
    text-align: right;
    float: right
}

.inbox ul.messages-list li .title {
    margin: 0 0 5px 0;
    white-space: nowrap;
    overflow: hidden!important;
    text-overflow: ellipsis
}

.inbox ul.messages-list li .description {
    font-size: 12px;
    padding-left: 29px
}

.inbox ul.messages-list li .action {
    display: inline-block;
    width: 16px;
    text-align: center;
    margin-right: 10px;
    color: #d1d4d7
}

.inbox ul.messages-list li .action .fa-check-square-o {
    margin: 0 -1px 0 1px
}

.inbox ul.messages-list li .action .fa-square {
    float: left;
    margin-top: -16px;
    margin-left: 4px;
    font-size: 11px;
    color: #fff
}

.inbox ul.messages-list li .action .fa-star.bg {
    float: left;
    margin-top: -16px;
    margin-left: 3px;
    font-size: 12px;
    color: #fff
}

.inbox .message .message-title {
    margin-top: 30px;
    padding-top: 10px;
    font-weight: 700;
    font-size: 14px
}

.inbox .message .header {
    margin: 20px 0 30px 0;
    padding: 10px 0 10px 0;
    border-top: 1px solid #d1d4d7;
    border-bottom: 1px solid #d1d4d7
}

.inbox .message .header .avatar {
    -webkit-border-radius: 2px;
    -moz-border-radius: 2px;
    border-radius: 2px;
    height: 34px;
    width: 34px;
    float: left;
    margin-right: 10px
}

.inbox .message .header i {
    margin-top: 1px
}

.inbox .message .header .from {
    display: inline-block;
    width: 50%;
    font-size: 12px;
    margin-top: -2px;
    color: #d1d4d7
}

.inbox .message .header .from span {
    display: block;
    font-size: 14px;
    font-weight: 700;
    color: #3d3f42
}

.inbox .message .header .date {
    display: inline-block;
    width: 29%;
    text-align: right;
    float: right;
    font-size: 12px;
    margin-top: 18px
}

.inbox .message .attachments {
    border-top: 3px solid #e4e5e6;
    border-bottom: 3px solid #e4e5e6;
    padding: 10px 0;
    margin-bottom: 20px;
    font-size: 12px
}

.inbox .message .attachments ul {
    list-style: none;
    margin: 0 0 0 -40px
}

.inbox .message .attachments ul li {
    margin: 10px 0
}

.inbox .message .attachments ul li .label {
    padding: 2px 4px
}

.inbox .message .attachments ul li span.quickMenu {
    float: right;
    text-align: right
}

.inbox .message .attachments ul li span.quickMenu .fa {
    padding: 5px 0 5px 25px;
    font-size: 14px;
    margin: -2px 0 0 5px;
    color: #d1d4d7
}

.inbox .contacts ul {
    margin-top: 30px;
    padding: 0;
    list-style: none
}

.inbox .contacts ul li {
    height: 30px;
    padding: 5px 15px;
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis!important;
    position: relative;
    cursor: pointer
}

.inbox .contacts ul li .label {
    display: inline-block;
    width: 6px;
    height: 6px;
    padding: 0;
    margin: 0 5px 2px 0
}

.inbox .contacts ul li:hover {
    background: #e4e5e6
}
    </style>


</head>
<body>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<link href="https://select2.github.io/dist/css/select2.min.css" rel="stylesheet">
<script src="https://select2.github.io/dist/js/select2.full.js"></script>
<div class="container">
<div class="row inbox">
	
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-body message">
				<p class="text-center" style="text-transform:uppercase; font-family:cursive; font-weight: 900">New Message</p>
	
				<form class="form-horizontal" role="form" action="{% url 'user:sendmessage' match %}" method="post">
				{% csrf_token %}
					<div class="form-group">
				    	<label for="to" class="col-sm-1 control-label">To:</label>
				    	<div class="col-sm-11">
                              <p class="form-control select2-offscreen" style="text-transform:capitalize; font-family:verdana"> {{match}} </p>
				    	</div>
				  	</div>
					<div class="form-group">
				    	<label for="Subject" class="col-sm-1 control-label">Subject:</label>
				    	<div class="col-sm-11">
                              <input type="text" maxlength="50" class="form-control select2-offscreen" id="subject" placeholder="Type Subject" name="subject" tabindex="-1" required>
				    	</div>
				  	</div>
					
					
				
				
				<div class="col-sm-11 col-sm-offset-1">
					
					
					<br>	
					
					<div class="form-group">
						<textarea class="form-control" id="message" name="message" rows="12" maxlength="500" placeholder="Write a new message" required></textarea>
					</div>
					
					<div class="form-group">	
						<button type="submit" class="btn btn-success">Send</button>
				</form>


						<a href="{% url 'user:matches' %}" class="btn btn-danger" >Discard</a> <br>
						
					</div>
				</div>	
			</div>	
 				<a style="color: gray" class="link" href="{% url 'user:main' %}">
                                               		 <td><i class="fa fa-home"></i> Home</td>
                                         		 </a>
				<p </p>
 				<a style="color: gray" class="link" href="{% url 'user:inbox' %}">
                                               		 <td><i class="fa fa-inbox"></i> Inbox</td>
                                         		 </a>
		</div>	
	</div><!--/.col-->		
</div>
</div>
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="https://netdna.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
    $("#to, #cc, #bcc").select2({tags:["team@bm.com", "ceo@bm.com", "cto@bm.com"]});
});
</script>
</body>
</html>



 <!--***************************************************************************************
*  REFERENCES

*  Title: Inbox-compose-message template
*  Author: Dey Dey 
*  Date: 4/5/2021
*  URL: https://www.bootdey.com/snippets/view/inbox-compose-message#html
*  Software License: MIT license 
***************************************************************************************-->

user/templates/user/index.html
{% load static %}
{% load socialaccount %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Welcome </title>
		<link rel="icon" type="image/x-icon" href="{% static 'user/assets/img/portfolio/uvalogo.jpg' %}" />  
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
		<link rel="stylesheet" href="{% static 'user/css/styles2.css' %}">
		<link href="css/animate.css" rel="stylesheet">
		<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
		<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
		<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	</head>
	<body style="overflow-y: hidden">
		<div class="header">
			<div class="container">
				<div class="row">
					<div class="col-md-8">
						<div class="header-left">
							<img src="{% static 'user/assets/img/portfolio/uvalogo2.png' %}" class="logo" alt="Logo">
						</div>
						<div class="top-title">		
							<h1 class="animated infinite bounceInDown"> Welcome, {{user.username}}! </h1>
							<h6 class="logo-title animated pulse">Good luck on your Hoommate Search :) </h6>
						</div>
					</div>
					<div class="col-md-4">
						<div class="menu">
							{% if user.is_authenticated %}

							{% if profile %}
							<li class="f-item-1"><a href="{% url 'user:search' %}">Hoommate Search Hunt</a></li>
							<li class="f-item-2"><a href="{% url 'user:matches' %}">Your Matches</a></li>
							<li class="f-item-2"><a href="{% url 'user:inbox' %}">Your Inbox</a></li>
							<li class="f-item-3"><a href="{% url 'user:newprofile' %}">Update Your Profile</a></li>
							<li class="f-item-4"><a href="{% url 'user:logout' %}">Log Out</a></li>
							{% else %}
							<li class="f-item-1"><a href="{% url 'user:newprofile' %}">Create your profile</a></li>
							{% endif %}
							{% endif %}
						</div>
					</div>
				</div>
			</div>
		</div>
	</body>
 <!-- Commenting out this footer for now, just because I wanted to remove the scrollable white space <footer></footer> -Nathan -->
</html>


 <!--***************************************************************************************
*  REFERENCES

*  Title: Cool Navigation Bar
*  Author: devfahim 
*  Date: 4/16/2021
*  URL: https://bootsnipp.com/snippets/O5q6l
*  Software License: MIT license 
***************************************************************************************-->

user/templates/user/profileList.html
<div class="mx-auto" style="width: 400px;">
    <h1>All Profiles</h1>
    {% if latest_profile_list %}
        <p>
            {% for profile in latest_profile_list %}
            <li><a href="{% url 'user:details' profile.id %}">{{ profile.name_text }}</a></li>
            {% endfor %}
        </p>
    {% else %}
    <p>No profiles are available.</p>
    {% endif %}
</div>
<a href="{% url 'user:main' %}">Go Back to Main Page</a>

user/templates/user/test.html
<!-- This is meant for testing the image file-->

<div class="col-md-12 border-bottom">


  <form action="{% url 'user:clearfilter'  %}" method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-outline-secondary btn-sm">Clear Filters</button>
  
  
  <p style = "font-family:cursive;font-size:14px;font-style:italic;">
       
    </p>
  
  </div>

</form>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
     {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>
  
  {% if prof %}
    <img src="{{ prof.profile_image.url}}" alt="connect" style="max-height:300px">
  {% endif %}